cask_args appdir: '/Applications'
tap 'caskroom/cask'

brew 'git'
brew 'bash-completion'
brew 'vim'
brew 'wget'
brew 'tree'
brew 'jq'
brew 'ghq'
brew 'peco'

cask 'google-chrome'
cask 'iterm2'
cask 'alfred'
cask 'dropbox'
cask 'bettertouchtool'
cask '1password'
cask 'slack'
cask 'google-japanese-ime'
cask 'docker'
cask 'caffeine'

mas 'Quiver', id: 866773894
