#!/usr/bin/env bash
#
# Bootstrap dotfiles

configure_vim() {
  echo "Configuring vim..."
  if [ -d ~/.vim ]; then
    rm -r ~/.vim
  fi
  ln -sf $(pwd)/vim/vim/  ~/.vim
  ln -sf $(pwd)/vim/vimrc ~/.vimrc
  git submodule update --init
  echo "Done"
}

configure_bash() {
  echo "Configuring bash..."
  ln -sf $(pwd)/bash/bash_profile ~/.bash_profile
  ln -sf $(pwd)/bash/bashrc       ~/.bashrc
  echo "Done"
}

configure_git() {
  echo "Configuring git..."
  ln -sf $(pwd)/git/gitconfig ~/.gitconfig
  echo "Done"
}

main() {
  configure_vim
  configure_bash
  configure_git
}

main "${@}"
