#!/usr/bin/env bash
#
# Bootstrap dotfiles

configure_vim() {
  echo "Configuring vim..."
  ln -s $(pwd)/vim/vimrc ~/.vimrc
  ln -s $(pwd)/vim/vim/  ~/.vim
  git submodule update --init
  echo "Done"
}

configure_bash() {
  echo "Configuring bash..."
  ln -s $(pwd)/bash/bash_profile ~/.bash_profile
  ln -s $(pwd)/bash/bashrc       ~/.bashrc
  echo "Done"
}

configure_git() {
  echo "Configuring git..."
  ln -s $(pwd)/git/gitconfig ~/.gitconfig
  echo "Done"
}

main() {
  configure_vim
  configure_bash
  configure_git
}

main "${@}"
