#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT="`pwd`"

set -e

echo ""
echo "  dotfiles"
echo ""

caution () {
  printf "\r\033[2K  \033[00;33m!\033[0m $1\n"
}

user () {
  printf "\r  \033[0;33m?\033[0m $1 "
}

log () {
  printf "\r\033[2K  \033[00;32m+\033[0m $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_files () {
  ln -s $1 $2
  log "Linked $1 to $2"
}

#
# Install Dotfiles
#
log "Installing dotfiles..."

  overwrite_all=false
  backup_all=false
  skip_all=false

for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
do
  dest="$HOME/.`basename \"${source%.*}\"`"

  if [ -f $dest ] || [ -d $dest ]
  then

    overwrite=false
    backup=false
    skip=false

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then
      caution "File already exists: `basename $source`, what do you want to do?"
      user "  [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?:"
      read -e -n 1 action

      case "$action" in
        o )
          overwrite=true;;
        O )
          overwrite_all=true;;
        b )
          backup=true;;
        B )
          backup_all=true;;
        s )
          skip=true;;
        S )
          skip_all=true;;
        * )
          skip_all=true;;
      esac
    fi

    if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
    then
      rm -rf $dest
      log "Removed $dest"
    fi

    if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
    then
      mv $dest $dest\.backup
      log "Moved $dest to $dest.backup"
    fi

    if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
    then
      link_files $source $dest
    else
      log "Skipped $source"
    fi

  else
    link_files $source $dest
  fi

done

#
# Initialize Submodule
#
log "Initiazing submodule..."
git submodule update --init

echo ""
echo "  All installed!"
